### ISSUE TITLE
Consider exposing even more things

### ISSUE THREAD

**Issue by lunaris** [i-am-tom/higgledy#10]
In https://github.com/lunaris/generic-validated/blob/master/src/Validated/Codes.hs#L35 I end up needing the `ProductBC` and `GAllB` classes/constraint families. I may be doing it wrong, but I think if one wants to write any polymorphic function that uses some of the `barbies` stuff these are necessary. Not sure if they are clean enough to export, or perhaps some class synonym like `class (ProductBC ..., GAllB ...) => BarbieHKD ...` would be the right call? Alternatively if there's another way of doing this then let me know.

**Comment by i-am-tom** [comment]
As far as I know, both of these can be exported from the `barbies` library, which seems like the "morally right" place to find them. However, I don't see any harm in re-exporting them from here, given how useful they are - I'll do so and bump the version :)
