### ISSUE TITLE
Haddock for Construct should probably mention Applicative

### ISSUE THREAD

**Issue by isovector** [i-am-tom/higgledy#13]
The haddock for `Construct` is:

```haskell
class Construct (f :: Type -> Type) (structure :: Type) where
  construct :: HKD structure f -> f structure
  deconstruct :: structure -> HKD structure f
```

and 

```haskell
(Functor f, Generic structure, GConstruct f (Rep structure)) => Construct f structureSource
```

this is pretty amazing and sounds like you can `deconstruct` for any `f` --- though it seems like it such a thing would require `pure`. Indeed the implementation has an `Applicative f` constraint, but this wigged me out for a few minutes!

**Comment by i-am-tom** [comment]
Yeah, this makes some obvious sense :flushed: I'll fix this now - thanks!
