### ISSUE TITLE
Allow 'build' with named fields

### ISSUE THREAD

**Issue by neongreen** [i-am-tom/higgledy#15]
Currently `build` is not great to use – you can mix up the field order:

```haskell
>>> :{
test :: _
test = build @User
:}
...
... • Found type wildcard ‘_’
...     standing for ‘f [Char] -> f Int -> f Bool -> HKD User f’
...
```

(Here you can't, but if there were two Ints, you could.)

I propose adding a version that uses the [`named`](http://hackage.haskell.org/package/named) library:

```haskell
test
    :: "name"      :! f [Char]
    -> "age"       :! f Int
    -> "likesDogs" :! f Bool
    -> HKD User f
test = buildNamed @User
```

Then the function can be called like this:

```haskell
test (#name ...) (#age ...) (#likesDogs ...)
```

Or in this style, which allows supplying the arguments in any order:

```haskell
test
    ! #likesDogs ...
    ! #name ...
    ! #age ...
```

**Comment by i-am-tom** [comment]
Oh wow, nice! I like this a lot. I'll play around this weekend and see what I can do, but I'm very into it! :)

**Comment by i-am-tom** [comment]
Sorry for how long it has taken to get back to this - I got sidetracked by talk-writing 😅 I've messed around with this a little, and I really like how it turns out, so I'll try to get a PR together this week if you're willing to review? :)

**Comment by neongreen** [comment]
Sure!

**Comment by i-am-tom** [comment]
I'll shut this thread and move us over to #16 - hopefully, it's not too far from what you had in mind! :)
