### ISSUE TITLE
using HKD from class methods

### ISSUE THREAD

**Issue by bbarker** [i-am-tom/higgledy#17]
I'm probably trying to do something that should not be done, but I added `recLabels` to a class I have:

```haskell
class (Eq a, IRes a, Generic a, Ord a, Read a, Show a, Typeable a)
  => IsDerivedRec a where
  -- ...
  tableName        :: TableName
  tableName        = type2tblName $ typeRep $ Proxy @a
  recLabels        :: Labels a
  recLabels        = label
```

Resulting in the error:

```haskell
  • Could not deduce (Data.Generic.HKD.Labels.GLabels
                          (GHC.Generics.Rep a))
        arising from a use of ‘label’
      from the context: IsDerivedRec a
        bound by the class declaration for ‘IsDerivedRec’
        at src/FDS/Data/IsRecord.hs:36:6-17
    • In the expression: label
      In an equation for ‘recLabels’: recLabels = label
   |
46 |   recLabels        = label
   |                      ^^^^^
```

Just curious if it is possible to make this work, or perhaps why not.

**Comment by bbarker** [comment]
Ah, I think I found the issue, I should have added `Label a`, instead of `Generic a` as GHC suggested, to the class prerequisites. Will report back.

**Comment by bbarker** [comment]
(well, got sidetracked, not surprising in generics land: https://stackoverflow.com/questions/58140677/what-is-giving-rise-to-unsolved-type-constraints-in-this-generic-lens-applicatio)

**Comment by i-am-tom** [comment]
You're right that `Label a` is indeed the correct constraint :) I'm on my phone at the moment, are you still having trouble?

**Comment by bbarker** [comment]
I haven't fully tested it but using `Label a` did seem to make it compile, so I'll close the issue. If you have a chance, the SO post above is related to making the syntax for accessing fields somewhat more concise - I could also open another issue if you prefer to discuss there.
