### ISSUE TITLE
Natural transformation on HKD types

### ISSUE THREAD

**Issue by cgeorgii** [i-am-tom/higgledy#32]
The [Barbies documentation](https://hackage.haskell.org/package/barbies-2.1.1.0/docs/Barbies.html#g:1) mentions a way to change the "outfits" of a barbie using `bmap`:
```hs
bmap (either (const Nothing) Just) (p :: Person (Either e))
```

If I try to write a function that uses `bmap` on an `HKD` type to achieve a similar effect, I get the following error:

```hs
data Wrapper a = Wrapped a | Unwrapped deriving (Generic)

f :: HKD a Wrapper -> HKD a Maybe
f x = bmap g x
  where
    g :: Wrapper a -> Maybe a
    g (Wrapped a) = Just a
    g Unwrapped = Nothing
```
Error:
```
• Could not deduce (Data.Generic.HKD.Types.GFunctorB (Rep a)) arising from a use of ‘bmap’
```
The `higgledy` documentation mentions:

> By combining this with some of the [Barbies](https://hackage.haskell.org/package/barbies) interface (the entirety of which is available to any HKD-wrapped type) [..]

I assumed using `bmap` would then just work. Am I doing something wrong? Is it possible to write such a transformation using `higgledy`?

**Comment by velveteer** [comment]
Can you share your definition of `HKD`? The traditional signature of the HKD type family is `HKD f a` and yours is flipped.

**Comment by velveteer** [comment]
I don't use higgledy but I think your type for `f` is too polymorphic. You can help GHC deduce this, but I don't think higgledy exports the class you need:

```haskell
f :: GFunctorB (Rep a) => HKD a Wrapper -> HKD a Maybe
```

Maybe there's another way.

**Comment by cgeorgii** [comment]
Yes, I believe this might be related to the other issue I created about unexported classes: https://github.com/i-am-tom/higgledy/issues/31

**Comment by i-am-tom** [comment]
Hey! Just like #31, you should just be able to add a constraint `FunctorB (HKD a)` and have this work happily :)

**Comment by cgeorgii** [comment]
It seems so obvious, but I couldn't figure out at the time! Thanks for the pointer, though, it works :)
