### ISSUE TITLE
Prefer Data.Semigroup.Last

### ISSUE THREAD

**Issue by jmackie** [i-am-tom/higgledy#4]
From the base-4.12.0 docs...

> This type will be marked deprecated in GHC 8.8, and removed in GHC 8.10. Users are advised to use the variant from Data.Semigroup and wrap it in Maybe.

So for example

```
>>> import Data.Semigroup (Last (..))
>>> type Partial a = HKD a (Maybe (Last a))
```

Dank library tho my man.

**Comment by i-am-tom** [comment]
Oh nice, I didn't know this!

Will update shortly, cheers :ok_hand:

**Comment by jmackie** [comment]
My bad, that should be

```
>>> type Partial a = HKD a (Compose Maybe Last)
```

**Comment by i-am-tom** [comment]
I haven't forgotten about this - just trying to find a way to phrase it that doesn't look much more complicated than what's already there!
