### ISSUE TITLE
Consider exporting all the things via Internal module and/or export a bit more

### ISSUE THREAD

**Issue by pacak** [i-am-tom/higgledy#7]
I keep doing strange things. Consider something like this:

```haskell

data Foo = Foo { int :: Int, bool :: Bool } deriving (Generic, ...)

-- uses Read instances to populate corresponding fields
fromPairs :: [(String, String)] -> HKD Foo Maybe

fromPairs [] == Foo Nothing Nothing
fromPairs [("int", "10")] = Foo (Just 10) Nothing
fromPairs [("bool", "False)] = Foo Nothing (Just False)
```
Implementation uses `label` internally and since it requires `HKD structure f` as input I'm using it as `label (mempty :: HKD Foo (Const ()))`. Now, any attempt to make it for any structure fails since required constraint `(Monoid tuple, Generic xs, Tuple f xs tuple) => Monoid (HKD xs f)` can't be expressed without `Tuple` class that's not exported.

Something-something _internals_ something (_if they could be exposed_).

https://stackoverflow.com/questions/9190638/how-why-and-when-to-use-the-internal-modules-pattern

**Comment by i-am-tom** [comment]
Aah, absolutely! I think `Tuple` is probably actually useful enough to be exported through the front door, rather than the back door for internals. I'll expose it now, and try to figure out what is left that could come through an internals module :)

**Comment by i-am-tom** [comment]
This is now hopefully fixed in `master`, and I'll push to Hackage shortly :) Can't guarantee I'll have too much time this week for sorting out an internals module, but I'll do my best!
